### ISSUE TITLE
Empty array in field return an error.

### ISSUE THREAD

**Issue by audiBookning** [TreeMan360/nestjs-graphql-dataloader#2] opened 2020-04-11 23:50 UTC
When a field in a query returns an empty array, even when he is not required, graphql returns an error:

> "message": "FooBar does not exist...

I see this comment in the ensureOrder function:

> // Loop through the keys and for each one retrieve proper document. For not
   // existing documents generate an error.

And you have this check following it:

```typescript
return (
      docsMap.get(key) ||
      new Error(typeof error === 'function' ? error(key) : error)
    );
```

The code should just ignore them as empty results.

**Comment by TreeMan360** [comment] 2020-04-12 07:14
I will look into this and get back to you.

**Comment by TreeMan360** [comment] 2020-04-15 11:15
Can you give me a concrete example of this please?

**Comment by audiBookning** [comment] 2020-04-15 16:08
The test that i had done with nestjs-graphql-dataloader was in a branch of an ongoing client project, but as soon as i can, i will do a minimal working example to share.

**Comment by audiBookning** [comment] 2020-04-15 18:49
When i was trying to create the MWE, i stumbled on another problem. So i ended wasting most of my available time in it and did not got to the model i needed. I believe that it would be preferable to solve this new one first, since it might solve the former also.

If you want i can open another issue in the repo for it.
In the meantime here is the example repo: [nest-dataloader-test](https://github.com/audiBookning/nest-dataloader-test)
note: I hope you don't mind it, but i have left the code full of console.log. I can clean it of you want.

I am not sure if it is something i am doing wrong because i am unfamiliar with DataLoader or if it is a real issue. What is your opinion?

**Comment by TreeMan360** [comment] 2020-04-15 20:58
I have only just had a very very quick look in my phone. But you need to use `postsLoader.load` for when you return a single entity. If you are returning an array you need to use `postLoader.loadMany.` I am using this in production without issues so I imagine that is the potential root of your problems?

**Comment by TreeMan360** [comment] 2020-04-15 22:00
```
  @ResolveField()
  async posts(@Parent() author: Author, @Loader(PostLoader) postLoader) {
    const { id } = author;
    console.log('AuthorsResolver posts id: ', id);
    const postsReturn = await postLoader.load(id);
    console.log('AuthorsResolver posts postsReturn: ', postsReturn);
    return postsReturn;
  }
```

1. ```@ResolveField(of => [Post])``` - Need to specify you are returning an array of posts
2. ```await postLoader.loadMany(ids)``` -  This is an array so you need to use loadMany. Also you need to pass in probably ```author.postIds``` to ```loadMany```.
3. Strongly typing your loader will help prevent issues e.g: ```@Loader(PostLoader) postLoader: DataLoader<Post['id'], Post>```

This would then match what I would expect with:

```
{
  findAllAuthors {
    id
    name
    posts {
      id
      title
    }
  }
}
```

If your example is a test attempt at returning a single ```post``` entity then this query would still work of course despite the mismatched naming. 

In your loader:

```
import { Injectable } from '@nestjs/common';
import { OrderedNestDataLoader } from 'nestjs-graphql-dataloader';
import { Post } from './models/post.model';
import { PostsService } from './posts.service';

@Injectable()
export class PostLoader extends OrderedNestDataLoader<Post['id'], Post> {
  constructor(private readonly postsService: PostsService) {
    super();
  }

  protected getOptions = () => {
    return {
      query: (keys: Array<Post['id']>) => {
        console.log('PostLoader keys: ', keys);
        // gives an error:
        // "message": "Expected Iterable, but did not find one for field \"Author.posts\".",
        const posts = this.postsService.findByAuthorsIds(keys);

        // findByAuthorsIdsRamda return an ordered array of posts by authorID
        // But nestjs-graphql-dataloader give an error "message": "Post does not exist (1)",
        // in the ensureOrder function
        // const posts = this.postsService.findByAuthorsIdsRamda(keys);
        console.log('PostLoader posts: ', posts);
        return posts;
      },
    };
  };
}
```
Firstly, from a design perspective you do not want to model your ```posts``` loader to use the ```authorId```. The ```PostLoader``` keys should always be ```post.id```. Then you would do what I said above - ```postLoader.load(author.postIds)``` with the implementation being ```this.postService.findByIds(keys)``` rather than ```.findByAuthorIds(...```.

Also if you want to try out your own ordering or implementation then do not use this as your foundation. You would instead inherit from ```NestDataLoader``` rather than ```OrderedNestDataLoader``` and do the standard ```dataloader``` implementation as per the ```dataloader``` documentation. An example of this would be:

```
...
import DataLoader from 'dataloader'
...
@Injectable()
export class PostLoader implements NestDataLoader<string, Post> {
  constructor(private readonly postService: PostService) {}

  public generateDataLoader(): DataLoader<string, Post> {
    return new DataLoader<string, Post>(keys =>
      this.postService.findByIds(keys as string[]),
    )
  }
}
```

As you state you are not returning a promise from your ```getOptions```.  Just wrap it in a promise for testing as in `return Promise.resolve(posts)`.

```
"message": "Post does not exist (1)",
```

This error is not coming from graphQL it is coming from the ```ensureOrder``` function in this package. 
This is because the key does not exist - probably because you aren't returning a promise.

```
// "message": "Expected Iterable, but did not find one for field \"Author.posts\".",
```

This is because ```Author.posts``` is not an array.

I think you have a few potential issues here but I believe they all reside within your code. Your use case is very typical and I am using this in production without issues. 

I hope that helps, sorry I don't have time to look any deeper into this I have just had a scan through the code. If you find a reproducible problem with a concrete, clean, **small** example then I will do my best to resolve any issues you may have. 

I should add some tests to this package which would help you understand the expected and unexpected use cases but I just pulled it out quickly into a package incase anybody found it useful.

**Comment by audiBookning** [comment] 2020-04-16 06:18
Thank you very much for taking the time to give such a detailed response.

> If you find a reproducible problem with a concrete, clean, **small** example then I will do my best to resolve any issues you may have.

I did think that i was giving the smallest example possible. Only 2 entities with simple relations. The alternative was to give wild code, but that probably would not have helped much in transmitting the situation. The earlier project i mentioned has already more than 40 entities...

> Also if you want to try out your own ordering or implementation then do not use this as your foundation. You would instead inherit from NestDataLoader rather than OrderedNestDataLoader and do the standard dataloader implementation as per the dataloader documentation.

That worked exactly like i wanted. Thanks.
Although it is a shame that i have to loose this package ordering for this specific entity relationship.

> Firstly, from a design perspective you do not want to model your posts loader to use the authorId. The PostLoader keys should always be post.id. Then you would do what I said above - postLoader.load(author.postIds) with the implementation being this.postService.findByIds(keys) rather than .findByAuthorIds(....

Using author.postIds is normal when dealing with noSQL databases like mongoDB, but it is not really an option with SQL. As you can see from the "Database entity models" in the example repo, the Author has no knowledge of postIds, only the Post has a reference to the author. So there is no author.postIds.

For the Author to be able to have that, the query of the resolver findAllAuthors would need to have a join on the Posts. but then there would be no need for the ResolveField of the Posts and also no need for Dataloader. And that join would be always executed whether the client ask for the posts or not.

Because of the ordering issue when using NestDataLoader directly, i ended putting some time in trying to hack some temporary solution by editing directly nestjs-graphql-dataloader.
I have updated the earlier repo and put the small changes in a "nestjs-graphql-dataloader.ts" in it.

They are working for the mean time, but they are not really deserving of a PR as there is too much still missing. I will revisit it in the later phases of the project i am doing now. Meanwhile the code is there and it might inspire you or someone else.

> I just pulled it out quickly into a package incase anybody found it useful.

I understand that maintaining anything need not a little time and energy. So i am always grateful for any simple sharing.

Thanks again and stay safe.

**Comment by TreeMan360** [comment] 2020-04-16 06:51
When I say small I mean strip out EVERYTHING that is not relevant to the example and push those things together so they are colocated so it’s nice and easy to look at and highlights the issue.

I am using SQL (Typeorm) and you can always query the ids via the inverse relationship. It should be pretty easy to reorientate to accommodate this. I did this on my large project when I introduced the loader without any hassle. This is however an exercise for yourself.

If you want to do things differently this is only a single file. Copy it into your project or fork it and reference it directly and the modify for your specific use case. 

I don’t want a PR for this as In my opinion you are trying to go against the grain. The loaders should store their data against the entities ID. This also allows them to be reused across resolvers which is where you get the most benefit.

You could make another loader perhaps such as PostsByAuthorIdLoader but I would not recommend this as I did this initially and quickly reverted to my above suggestions.

I am going to close this issue as I don’t think there is an issue with this library here but if you can pinpoint something as I said I will be happy to look at it again under a new issue.

Good luck and stay safe yourself in these crazy times.

**Closed as completed by TreeMan360** 2020-04-16 06:51 UTC

**Comment by TreeMan360** [comment] 2020-04-16 07:16
Just a couple of final points:

```
  protected getOptions = () => {
    return {
      query: (keys: Array<Post['id']>) => {
        return this.postsService.findByAuthorsIds(keys);
      },
      returnType: ReturnType.Array,
      propertyKey: 'authorId',
    };
```

```
  protected createLoader(
    options: IOrderedNestDataLoaderOptions<ID, Type>,
  ): DataLoader<ID, Type> {
    const defaultTypeName = this.constructor.name.replace('Loader', '');
    const ensureOrderFn =
      options.returnType === ReturnType.Array
        ? ensureOrderArray
        : ensureOrderObject;
```

I really do not understand this. As I said should ALWAYS return an array from a `dataloader`, that is the whole point. I would do some reading on how the internals of the `dataloader` work:

https://github.com/graphql/dataloader
https://www.yld.io/blog/demystifying-the-graphgl-dataloader-utility-there-is-no-magic/

It is effectively collecting all the ids required for your graphQL request and then the loader is called so that one database request happens for all those ids thus avoiding the classic N+1 problem. So by its very nature it will always work with an array of ids, whether your specific consumer (in this case field resolver) wants a single or multiple entities this makes no difference.

**Comment by audiBookning** [comment] 2020-04-16 18:37
Being  truthful, i must say that Uncle Bob would not be really happy with my naming convention.

> I really do not understand this. As I said should ALWAYS return an array from a dataloader

You may be referring to the ReturnType enum? The wording is not very good but it is only a draft wording and it it is only indicating the type of ordering to choose: array of objects or array of arrays. It is always returning returning an array at the minimum.

> I am using SQL (Typeorm) and you can always query the ids via the inverse relationship.

I am not really seeing how you do that. Unless you are talking about 
[Typeorm relations](https://typeorm.io/#/relations)?
From what i understand that is a join operation. Typeorm is only hiding it to facilitate the orm interface.

> You could make another loader perhaps such as PostsByAuthorIdLoader

Yes that would be a much better name for the loader and its intention.

I do understand why you insist that the loaders should be more specific and i see the advantages like the ability to reuse a PostLoader in any resolver. but i don't think it is really possible.

From what i understand, the loaders should not be seen as entity caches. They are nearer to caches of "relations of an entitý". The "special" ordering of the cache is a good indication for that. Unfortunately this vision has the great disadvantage that one would have as many loaders as relations to that entity: PostsByAuthorIdLoader, PostsByFooIdLoader, PostsByBarId Loader, etc And all those Posts would be separated and could not be reused :(

**Comment by TreeMan360** [comment] 2020-04-16 19:06
You are missing my points on a few levels here I am afraid. If I have the time I will write a full response to this explaining but for now I imagine you will come to understand over time. 

But primarily no I don’t have a problem with your naming convention my problem is that there is absolutely no reason to have the added returnType at all. As I have stated a few times now It is ALWAYS an ARRAY of ids - ALWAYS! :) 

With respect to the relations I query the ids along with the parent entity and then those ids are available to the field resolvers. Yes this involves a join operation but this happens once at the parent and then all field resolvers resolve in a single select query rather than a query for each entity id in the collection. It also means other parts of the graph that also include the same entity are only queried once. These two things equate to a massive performance improvement.

Going down your route you will not reap the same benefits as you have many more loaders so they won’t get reused as effectively.

Yes, it is not perfect but it’s a hell of a lot faster than without the dataloader.

I would recommend running with SQL logging on and trying lots of deep queries and you will see the impact first hand.

**Comment by lightning003** [comment] 2021-06-03 09:06
Bit of an old thread but I think I am understanding both the points. I ended up in similar situation few weeks back and yes author does not have any info on postIds without hitting db query so I ended up having two loaders 
-> one loader will fetch array of post ids for each author so autorId -> postIds[]
-> another loader will be postLoader normal one so postId -> Post.

@TreeMan360  ... I noticed you said you added two loaders one time and reverted that approach, may I ask what issue you faced or what were your thoughts then?
